/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package calculator;

import calculator.ast.ASTNode;
import calculator.ast.NumberASTNode;
import calculator.ast.binary.AddBinaryASTNode;
import calculator.ast.binary.MulBinaryASTNode;
import calculator.ast.unary.MinusUnaryASTNode;
import calculator.visitor.EvaluateVisitor;
import calculator.visitor.IVisitor;
import calculator.visitor.PrintVisitor;

public class App {
    public static void main(String[] args) {
        ASTNode node = new AddBinaryASTNode(
                new NumberASTNode(42),
                new MulBinaryASTNode(
                        new MinusUnaryASTNode(
                                new NumberASTNode(21)
                        ),
                        new NumberASTNode(2)
                )
        );

        PrintVisitor printVisitor = new PrintVisitor();
        node.accept(printVisitor);

        EvaluateVisitor evaluateVisitor = new EvaluateVisitor();
        int result = node.accept(evaluateVisitor);

        System.out.println("=" + result);
    }
}
