/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package calculator;

import calculator.ast.ASTNode;
import calculator.token.exception.InvalidTokenException;
import calculator.parser.exception.UnexpectedTokenException;
import calculator.lexer.Lexer;
import calculator.parser.Parser;
import calculator.visitor.EvaluateVisitor;
import calculator.visitor.PrintVisitor;

import java.io.ByteArrayInputStream;
import java.util.Scanner;

public class App {
    public static final Scanner SCANNER = new Scanner(System.in);

    public static void main(String[] args) throws InvalidTokenException, UnexpectedTokenException {
        System.out.print("Enter an expression: ");
        String expr = SCANNER.nextLine();
        byte[] bytes = expr.trim().getBytes();

        Lexer lexer = new Lexer(new ByteArrayInputStream(bytes));
        Parser parser = new Parser(lexer);
        ASTNode node = parser.parseExpr();

        PrintVisitor printVisitor = new PrintVisitor();
        node.accept(printVisitor);

        EvaluateVisitor evaluateVisitor = new EvaluateVisitor();
        int result = node.accept(evaluateVisitor);

        System.out.println("=" + result);
    }
}
